import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'

import { createUser, deleteUser, fetchUsers, updateUser, type User } from '../../api/users'
import { fetchCourseCategories } from '../../api/management'

type ManagedRole = 'teacher' | 'student'
type FormState = { name: string; email: string; password: string; password_confirmation: string; phone: string; avatar_url: string; bio: string; specialty: string; academic_id: string; teaching_category_id: string; status: 'active' | 'inactive' }
const emptyForm: FormState = { name: '', email: '', password: '', password_confirmation: '', phone: '', avatar_url: '', bio: '', specialty: '', academic_id: '', teaching_category_id: '', status: 'active' }

export default function UserManagementPage({ role }: { role: ManagedRole }) {
  const queryClient = useQueryClient()
  const [search, setSearch] = useState('')
  const [editing, setEditing] = useState<User | null>(null)
  const [form, setForm] = useState<FormState>(emptyForm)
  const [isFormOpen, setIsFormOpen] = useState(false)
  const isTeacher = role === 'teacher'
  const label = isTeacher ? 'المعلمين' : 'الطلاب'
  const usersQuery = useQuery({ queryKey: ['users', role], queryFn: () => fetchUsers(role) })
  const categoriesQuery = useQuery({ queryKey: ['course-categories'], queryFn: fetchCourseCategories, enabled: isTeacher })
  const closeForm = () => { setEditing(null); setForm(emptyForm); setIsFormOpen(false) }
  const saveMutation = useMutation({ mutationFn: () => editing ? updateUser(editing.id, { ...form, teaching_category_id: form.teaching_category_id ? Number(form.teaching_category_id) : undefined, password: form.password || undefined, password_confirmation: form.password_confirmation || undefined, role }) : createUser({ ...form, teaching_category_id: form.teaching_category_id ? Number(form.teaching_category_id) : undefined, role }), onSuccess: () => { closeForm(); queryClient.invalidateQueries({ queryKey: ['users', role] }) } })
  const deleteMutation = useMutation({ mutationFn: deleteUser, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['users', role] }) })
  const openEdit = (user: User) => { setEditing(user); setIsFormOpen(true); setForm({ name: user.name, email: user.email, password: '', password_confirmation: '', phone: user.phone ?? '', avatar_url: user.avatar_url ?? '', bio: user.bio ?? '', specialty: user.specialty ?? '', academic_id: user.academic_id ?? '', teaching_category_id: user.teaching_category_id ? String(user.teaching_category_id) : '', status: user.status }) }
  const filteredUsers = (usersQuery.data ?? []).filter((user) => `${user.name} ${user.email} ${user.academic_id ?? ''} ${user.specialty ?? ''}`.toLowerCase().includes(search.toLowerCase()))
  const updateField = (field: keyof FormState, value: string) => setForm((current) => ({ ...current, [field]: value }))

  if (usersQuery.isLoading || (isTeacher && categoriesQuery.isLoading)) return <div className="py-16 text-center text-slate-500">جاري تحميل {label}...</div>
  if (usersQuery.isError || (isTeacher && categoriesQuery.isError)) return <div className="py-16 text-center text-rose-600">تعذر تحميل بيانات {label}</div>
  const categories = categoriesQuery.data ?? []

  return <div className="space-y-6">
    <header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-blue-600">إدارة المستخدمين</p><h1 className="mt-1 text-3xl font-bold text-slate-900">{label}</h1><p className="mt-2 text-slate-500">ملفات كاملة وحسابات قابلة للإدارة</p></div><button type="button" onClick={() => { setEditing(null); setForm({ ...emptyForm }); setIsFormOpen(true) }} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-700">+ إضافة {isTeacher ? 'معلم' : 'طالب'}</button></header>
    <section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث بالاسم أو البريد أو الرقم الأكاديمي" className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500 sm:max-w-md" /><span className="text-sm text-slate-500">{filteredUsers.length} مستخدم</span></section>
    {isFormOpen ? <form onSubmit={(event) => { event.preventDefault(); saveMutation.mutate() }} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2"><h2 className="text-lg font-bold text-slate-900 md:col-span-2">{editing ? 'تعديل الملف' : `إضافة ${isTeacher ? 'معلم' : 'طالب'}`}</h2>{([['name', 'الاسم الكامل'], ['email', 'البريد الإلكتروني'], ['phone', 'رقم الهاتف'], ['academic_id', 'الرقم الأكاديمي'], ['specialty', 'التخصص'], ['avatar_url', 'رابط الصورة'], ['password', editing ? 'كلمة مرور جديدة' : 'كلمة المرور'], ['password_confirmation', 'تأكيد كلمة المرور']] as const).map(([field, placeholder]) => <input key={field} required={['name', 'email'].includes(field) || (!editing && ['password', 'password_confirmation'].includes(field))} type={field.includes('password') ? 'password' : 'text'} value={form[field]} onChange={(event) => updateField(field, event.target.value)} placeholder={placeholder} className="rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500" />)}{isTeacher && <select required value={form.teaching_category_id} onChange={(event) => updateField('teaching_category_id', event.target.value)} className="rounded-xl border border-slate-200 px-4 py-3"><option value="">تصنيف تدريس المعلم</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select>}<textarea value={form.bio} onChange={(event) => updateField('bio', event.target.value)} placeholder="نبذة تعريفية" className="min-h-24 rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500 md:col-span-2" /><select value={form.status} onChange={(event) => updateField('status', event.target.value)} className="rounded-xl border border-slate-200 px-4 py-3"><option value="active">نشط</option><option value="inactive">غير نشط</option></select><div className="flex gap-3 md:col-span-2"><button disabled={saveMutation.isPending} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white disabled:opacity-50">{saveMutation.isPending ? 'جاري الحفظ...' : 'حفظ البيانات'}</button><button type="button" onClick={closeForm} className="rounded-xl border border-slate-200 px-5 py-3 text-slate-700">إلغاء</button></div>{saveMutation.isError && <p className="text-rose-600 md:col-span-2">تعذر حفظ البيانات، تحقق من الحقول.</p>}</form> : null}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-right"><thead className="bg-slate-50 text-sm text-slate-500"><tr>{['المستخدم', 'التواصل', 'التخصص', 'النبذة', 'الحالة', 'الإجراءات'].map((heading) => <th key={heading} className="px-5 py-4 font-semibold">{heading}</th>)}</tr></thead><tbody>{filteredUsers.map((user) => <tr key={user.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-3"><img src={user.avatar_url ?? `https://ui-avatars.com/api/?name=${encodeURIComponent(user.name)}&background=e2e8f0&color=334155`} alt="" className="h-11 w-11 rounded-full object-cover" /><div><p className="font-semibold text-slate-900">{user.name}</p><p className="text-xs text-slate-500">{user.academic_id ?? 'بدون رقم أكاديمي'}</p></div></div></td><td className="px-5 py-4"><p className="text-slate-700">{user.email}</p><p className="text-xs text-slate-500">{user.phone ?? 'بدون هاتف'}</p></td><td className="px-5 py-4 text-slate-600">{user.specialty ?? 'غير محدد'}</td><td className="max-w-xs px-5 py-4 text-sm text-slate-500">{user.bio ?? 'لا توجد نبذة'}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${user.status === 'active' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{user.status === 'active' ? 'نشط' : 'غير نشط'}</span></td><td className="px-5 py-4"><button onClick={() => openEdit(user)} className="ml-3 text-blue-600">تعديل</button><button disabled={deleteMutation.isPending} onClick={() => confirm(`حذف ${user.name}؟`) && deleteMutation.mutate(user.id)} className="text-rose-600 disabled:opacity-50">حذف</button></td></tr>)}</tbody></table></div>{filteredUsers.length === 0 && <p className="p-12 text-center text-slate-500">لا توجد نتائج مطابقة</p>}</section>
  </div>
}