export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
  },
  MANAGEMENT: {
    LOOKUPS: '/dashboard/lookups',
    ACADEMIES: '/dashboard/academies',
    DEPARTMENTS: '/dashboard/departments',
    COMPETENCIES: '/dashboard/competencies',
    QUESTIONS: '/dashboard/questions',
    ASSESSMENTS: '/dashboard/assessments',
    TRAINING_PLANS: '/dashboard/training-plans',
    COURSES: '/dashboard/courses',
    COURSE_CATEGORIES: '/dashboard/course-categories',
    COURSE_INSTRUCTORS: '/dashboard/course-instructors',
    CERTIFICATES: '/dashboard/certificates',
    AUDIT_LOGS: '/dashboard/audit-logs',
  },
  TEACHER: {
    COURSES: '/teacher/courses',
    COURSE: (courseId: number) => `/teacher/courses/${courseId}`,
    MEDIA: (courseId: number) => `/teacher/courses/${courseId}/media`,
    CONTENT_MEDIA: (courseId: number, type: string, contentId: number) => `/teacher/courses/${courseId}/${type}/${contentId}/media`,
    LESSONS: (courseId: number) => `/teacher/courses/${courseId}/lessons`,
    WORKSHOPS: (courseId: number) => `/teacher/courses/${courseId}/workshops`,
    LECTURES: (courseId: number) => `/teacher/courses/${courseId}/lectures`,
  },
  ASSESSMENTS: {
    BY_ID: (assessmentId: number) => `/assessments/${assessmentId}`,
    AUTO_SAVE: '/assessments/auto-save',
    SUBMIT: (attemptId: number) => `/assessments/${attemptId}/submit`,
    ATTEMPTS: (assessmentId: number) => `/assessments/${assessmentId}/attempts`,
    ATTEMPT_DETAILS: (attemptId: number) => `/assessments/attempts/${attemptId}`,
  },
  DASHBOARD: {
    INDEX: '/dashboard',
  },
} as const
